export const resources = `
county	city	organization	phone	website	description	filter_tags	tags	address
National	National	(Information and Technical Assistance with) The Americans with Disabilities Act	ADA Information Line 800-514-0301 (voice); 800-514-0383 (TTY)	https://www.ada.gov/infoline.htm	The Department of Justice operates a toll-free ADA Information Line to provide information and materials to the public about the requirements of the ADA. ADA Specialists, who assist callers in understanding how the ADA applies to their situation, are available on Monday, Tuesday, Wednesday, and Friday from 9:30 a.m. until 5:30 p.m. (Eastern Time) and on Thursday from 12:30 p.m. until 5:30 p.m. (Eastern Time). Calls are confidential.	Legal/Housing	Legal AId, Civil Rights	U.S. Department of Justice 950 Pennsylvania Avenue, NW, Civil Rights Division, Disability Rights Section - NYA , Washington, D.C. 20530
Santa Clara	San Jose	Affordable Housing Search Center	1-877-428-8844	http://www.scchousingsearch.org/	Free housing search database and support center.	Legal/Housing	Housing	PO Box 35305, Charlotte, NC, 28235
Santa Clara	San Jose	ASIAN AMERICANS FOR COMMUNITY INVOLVEMENT OF SANTA CLARA COUNTY, INC	  408-975-2730	http://aaci.org/	It’s not uncommon for Asians and other minorities to feel uncomfortable seeking and receiving services due to language and cultural barriers. The team of multicultural and multilingual professionals at AACI works to bridge these gaps through an array of services and programs in health, recovery, advocacy, shelter and community. The AACI team includes the following specialists: Physicians, Psychiatrists, Psychologists, Social workers, Marriage and family therapist, Teachers, Health educators, Domestic violence prevention specialists.	Shelter	Senior Support, Cultural Empowerment	2400 Moorpark Ave, San Jose, CA 95128
Santa Clara	San Jose	Asian Law Alliance	(408) 287-9710	http://asianlawalliance.org/	Provides free legal representation to tenants with housing problems.	Legal/Housing	Legal Aid	991 W Hedding St, San Jose, CA 95126
Santa Clara	Los Gatos	Bay Area Housing Corporation	408-975-2730	http://bahc1.org/	Bay Area Housing Corporation’s mission is to improve the lives of people with developmental disabilities and their families and other low income populations by creating and maintaining quality housing opportunities that meet the needs of the individual.	Legal/Housing	Housing, disabilities	101 Church Street, Suite 4, Los Gatos, CA 95030
Santa Clara	San Jose	Bay Area Legal Aid	(408) 850-7066	https://baylegal.org/	Provides free legal representation to low-income tenants with housing problems.	Legal/Housing	Legal Aid, County	4 N 2nd St #600, San Jose, CA 95113
Santa Clara	Santa Clara	BILL WILSON CENTER	  1-408-243-0222	http://www.billwilsoncenter.org	The Homeless Youth Drop-In Center, located in downtown San Jose, is a safe place where young people can begin to form bonds with caring adults and access essential resources for their overall well-being. The primary goal of the program is to get homeless youth into safe and permanent housing.	Shelter	Housing, Shelter, counseling	3490 The Alameda, Santa Clara, CA 95050
State WIde	State WIde	California Department of Fair Employment and Housing	1-800-233-3212	http://www.dfeh.ca.gov/	State agency responsible for taking complaints of housing discrimination.	Legal/Housing	Discrimination, State	mailing: 2218 Kausen Drive, Suite 100, Elk Grove, CA 95758
Santa Clara	San Jose 	CATHOLIC CHARITIES OF SANTA CLARA COUNTY	  408-846-0428	http://www.ccsj.org	We help people of all cultures and beliefs rise up out of poverty and overcome the barriers to self-sufficiency. including job skills training and placement, older adult services, mental health and substance abuse counseling, housing assistance, financial education, immigration support, and refugee resettlement.	Legal/Housing	RLEI, Housing, Mental heatlh, DACA renewals, Community Development	2625 Zanker Rd, San Jose, CA 95134
Santa Clara	Campbell	CITY OF CAMPBELL RECREATION AND COMMUNITY SERVICES	  1-408-866-2764	http://www.cityofcampbell.com/135/Housing	Services include landlord tenant disputes, rental increase meditation, affordable housing referrals, first time home buyer program, and home repair loans	Legal/Housing	Recreation, Community	Campbell Community Center, 1 W. Campbell Ave., Office C-31, Campbell, CA 95008
Santa Clara	San Jose 	City of San Jose - Code Enforcement 	(408)535-7770	http://www.sanjoseca.gov/codeEnforcement	Enforces Housing Code and other City code.	Legal/Housing	Housing	200 E Santa Clara St, San Jose, CA 95113
Santa Clara	San Jose 	City of San Jose - Rental Rights & Referral Program	(408)975-4480	http://www.sanjoseca.gov/index.aspx?NID=743	Rent increases and service reductions in mobilehomes and most tri-plex and larger buildings built before 9/7/79.	Legal/Housing	Housing	200 E. Santa Clara St., San Jose, CA 95113
Santa Clara	San Jose	CITY OF SUNNYVALE COMMUNITY SERVICES	  1-408-730-7360	http://svcommunityservices.org/	Sunnyvale Community Services provides emergency assistance, information/referral services, and food programs to families, individuals, and seniors living in Sunnyvale zip codes: 94085, 94086, 94087, 94088, and 94089.	Legal/Housing	Education, Seniors	725 Kifer Rd, Sunnyvale, CA 94086
Santa Clara	San Jose	​City Team – Rescue Mission	408-288-2153	https://www.cityteam.org/san-jose/	Overnight emergency shelter for men; check-in begins at 5:30 p.m. First come, first served.	Shelter	Adult shelter	1174 Old Bayshore Highway, San Jose, CA 95112
San Mateo County	East Palo Alto 	Community Legal Services East Palo Alto	650-326-6440	https://clsepa.org/	Provides free legal aid to tenants.	Legal/Housing	Outside San Jose, Legal Aid	1861 Bay Road East Palo Alto, CA 94303
Santa Clara	Mountain View	COMMUNITY SERVICES AGENCY OF MOUNTAIN VIEW AND LOS ALTOS	  1-650-964-6586	https://www.csacares.org/services/homeless-services/	CSA homeless case managers assist with: Information to locate and secure affordable housing, assistance with public transportation, benefits and health services. Financial assistance with one month’s rent once clients, and secure employment and a place to live that fits within their budget. Food is also available through our Food & Nutrition Center	Legal/Housing	Recreation, Community, San Jose	204 Stierlin Rd, Mountain View, CA 94043
Santa Clara	Palo Alto	COMMUNITY WORKING GROUP - OPPORTUNITY CENTER	(650) 299-8700	https://communityworkinggroup.org/cwg-housing/opportunity-center/	Offers drop-in services, showers and laundry facilities, lockers, light snacks, information and referral, transportation assistance, a clothes closet, medical and psychiatric screening and referral, inter-faith chaplaincy, and fellowship.	Shelter	Community, Supportive Housing	2507-A Alma Street Palo Alto, CA 94301
Santa Clara	Gilroy	GILROY COMPASSION CENTER	  1-408-763-7120	https://gilroycompassioncenter.blogspot.com/	Offers bathroom, resource listings, jackets, clothing, telephone, the internet, laundry, mail, messages, compassion, and respite from the street. Shower, laundry, and medical service available every Thursday starting at 10am and finishing at 12pm. Hot Meals.	Shelter	Resources	370 Tomkins Ct, Gilroy, CA 95020
Santa Clara	San Jose	HomeFirst - Veterans Services	408-510-7522	https://www.homefirstscc.org/our-programs/	Emergency Shelter and Transitional Housing for veterans; veterans can access first come first served shelter beds (check in at 3:30 p.m.) before being screened for veteran bed eligibility.	Shelter	Shelters for Veterans 	2011 Little Orchard Street, San Jose, CA, 95125
Santa Clara	San Jose	HomeFirst – Boccardo Reception Center	408-294-2100	https://www.homefirstscc.org/our-programs/	Emergency shelter for men and women; check-in begins at 3:30 p.m. First come, first served.	Shelter	Shelter for Adults Without Children	2011 Little Orchard Street, San Jose, CA 95125
Santa Clara	San Jose	Santa Clara County Housing Authority	(408) 275-8770	https://www.scchousingauthority.org/contact/	Provides affordable housing assistance and manages the Housing Choice Voucher (Section 8) program.	Legal/Housing	Housing, Section 8	505 West Julian Street, San José, CA 95110
Santa Clara	San Jose	Housing Helpline	(408) 510-7600	http://www.sanjoseca.gov/index.aspx?NID=738	Information on service agencies and housing opportunities for homeless individuals.	Legal/Housing	Housing	200 E. Santa Clara St., San Jose, CA 95113
National	National	US Department of Housing and Urban Development	1-800-569-4287	https://www.hud.gov/i_want_to/talk_to_a_housing_counselor	Advice on buying a home, renting, default, foreclosure avoidance, credit issues or reverse mortgages.	Legal/Housing	Housing	U.S. Department of Housing and Urban Development 451 7th Street S.W., Washington, DC 20410
Santa Clara	Los Gatos	Information and Referral Services	(408) 243-8565	https://sanjoseca.gov/DocumentCenter/View/9543	Collection of resources and referrals for renters.	Legal/Housing	n/a	n/a
Santa Clara	Campbell	Information and Referral Services  	(408) 243-8565	https://sanjoseca.gov/DocumentCenter/View/9543	Collection of resources and referrals for renters.	Legal/Housing	Mediation, Counseling	n/a
Santa Clara	San Jose	Law Foundation of Silicon Valley - Fair Housing Law Project	(408) 280-2452	http://www.lawfoundation.org/fair-housing-law-project-fhlp	Provides free legal representation to victims of housing discrimination.	Legal/Housing	Discimination, Legal Aid, County	152 North 3rd Street, 3rd Floor, San Jose, CA 95112
Santa Clara	San Jose	Law Foundation of Silicon Valley - Health Legal Services	(408) 280-2430	http://www.lawfoundation.org/health-legal-services-hls/	Provides free legal representation to individuals with HIV/AIDS or diabetes who have housing problems.	Legal/Housing	Legal Aid, Elderly/Disabled, County	152 North 3rd Street, 3rd Floor, San Jose, CA 95112
Santa Clara	San Jose	Law Foundation of Silicon Valley - Mental Health Advocacy Project	(408) 280-2420 	http://www.lawfoundation.org/mental-health-advocacy-project-mhap/	Provides free legal representation to mental health and developmental services consumers who have housing problems.	Legal/Housing	Legal Aid, Elderly, Disabled, County	152 North 3rd Street, 3rd Floor, San Jose, CA 95112
Santa Clara	San Jose	LifeMoves – Georgia Travis House	408-271-1630	https://lifemoves.org/the-problem/get-help/santa-clara-county/	Shelter for women; call for more information.	Shelter	Shelter for Adults Without Children	260 Commercial Street San Jose, CA 95112
Santa Clara	San Jose	LifeMoves – Montgomery Street Inn	408-271-5160	https://lifemoves.org/the-problem/get-help/santa-clara-county/	Emergency shelter for men; program assessments Monday through Friday at 12:30 p.m.	Shelter	Shelter for Adults Without Children	358 North Montgomery Street, San Jose, CA 95110
Santa Clara	Los Altos	Los Altos Mediation Program	(650) 949-5267	http://losaltoscf.org/losaltosdispute/about-the-los-altos-dispute-resolution-services/	Information and mediation	Legal/Housing	Outside San Jose, Counseling	1490 El Camino Real, Santa Clara, CA 95050
Santa Clara	Los Gatos	Los Gatos Information and Referral Services	(408)243-8565	https://www.losgatosca.gov/DocumentCenter/View/8792	Information, counseling and mediation Apartment and mobilehome rent control	Legal/Housing	Outside San Jose, Counseling	110 E. Main St., Los Gatos, CA 95030
Santa Clara	Mountain View 	MTVW Information and Referral	(650) 960-0495	http://santaclara.networkofcare.org/mh/services/agency.aspx?pid=ProjectSentinelSunnyvale_356_2_0	Provides information and counseling on tenant/landlord rights and responsibilities. Conciliation and mediation services available for rental housing, and neighborhood disputes. Serves Cupertino, Milpitas, Mountain View ((650) 960-0495), Santa Clara, Sunnyvale, Campbell, Palo Alto ((650) 856-4062), Los Gatos ((408) 402-0307), Gilroy, Morgan Hill.	Legal/Housing	Legal Aid, Housing	554 Valley Way, Milpitas, CA 95035
Santa Clara	Palo Alto 	Palo Alto Mediation Service	(650) 856-4062	http://www.tenantstogether.org/resources/palo-alto-mediation-program	Information, counseling and mediation.	Legal/Housing	Outside San Jose, Counseling	450 Bryant Street, Palo Alto, CA 94301
Santa Clara	San Jose	Pro Bono Project Lawyers in the Library	(408) 808-2382	https://events.sjpl.org/event/lawyers_in_the_library_spring2016	Provides free 20-minute legal consultation on a variety of legal matters.	Legal/Housing	Legal Aid	Dr. Martin Luther King, Jr. Library, Room 255, 150 E. San Fernando St. San José, CA 95112
Santa Clara	Fremont	Project Sentinel	1-888-331-3332	http://housing.org/	Provides a variety of services (including mediation services) and advice regarding landlord-tenant problems in some jurisdictions.  Investigates claims of housing discrimination.	Legal/Housing	Legal Aid, Discrimination	39155 Liberty Street, Ste. D440, Fremont, CA 94538
Santa Clara	San Jose	Senior Adult Legal Assistance	408 295-5991	http://www.sala.org/	Legal assistance for individuals 60+ years old. Free legal assistance with: Housing, public benefits, long term care, elder abuse, etc.	Legal/Housing	Legal Aid, Elderly	1425 Koll Circle, Suite 109, San Jose, CA 95112
Santa Clara	San Jose	Salvation Army – Emmanuel House	408-282-1175	 http://www.salvationarmysiliconvalley.org/santaclara/emmanuel_house	Emergency shelter for men; suggested arrival time is between 1:30 p.m. to 2:30 p.m.	Shelter	Shelter for Adults Without Children	405 North Fourth Street, San Jose, CA 95112
Santa Clara	San Jose	Santa Clara County Bar Association Lawyer Referral	(408)287-2557	https://www.sccba.com/?lrs	Referrals to private attorneys (commercial rent disputes, other legal problems)	Legal/Housing	Legal Aid, Dispute Resolution	31 North 2nd St., Ste. 400, San Jose, CA 95113
Santa Clara	San Jose	SCC Department of Human Relations, Dispute Resolution Services	(408) 792-2314	https://www.sccgov.org/sites/ohr/Community/Pages/default.aspx	Provides low cost neutral-third-party dispute resolution services between tenants and landlords, tenants and other tenants, and neighbors.	Legal/Housing	Dispute Resolution	2310 North 1st Street, Suite 100, San Jose, CA 95131
Santa Clara	San Jose	Senior Adult Legal Assistance	(408)295-5991	http://www.sala.org/	Legal assistance for individuals 60+ years old.	Legal/Housing	Legal Aid, Elderly, Disabled	160 E Virginia St, San Jose, CA 95112
Santa Clara	San Jose	Sheriff's Office Civil Division  	(408) 808-4800	https://www.sccgov.org/sites/sheriff/Pages/civil.aspx	Information on evictions, fees and levies.	Legal/Housing	Law Enforcement	55 West Younger Ave., San Jose CA 95110
Santa Clara	San Jose 	SJPD Non-Emergency Line  	(408) 277-8900	http://www.sjpd.org/InsideSJPD/PhoneList.html	Assistance with civil standbys and other non-emergency issues .	Legal/Housing	Law Enforcement	201 W Mission Street, San Jose, CA 95110
Santa Clara	San Jose 	Small Claims Advisor 	(408) 882-2100 (option #2, 6)	https://www.lawhelpca.org/org/santa-clara-superior-court-small-claims-advisor	Information on starting a claim, going to court, and questions about judgments.	Legal/Housing	Legal Aid, Information	191 N 1st St, San Jose, CA 95113
Santa Clara	San Jose 	Superior Court - Civil Division 	(408) 882-2700	http://www.scscourt.org/court_divisions/civil/civil_home.shtml	Information on civil cases, civil filings, Unlawful Detainers (eviction), and Alternative Dispute Resolution (ADR) .	Legal/Housing	Legal	191 N 1st St, San Jose, CA 95113
San Francisco County	San Francisco	Tenants Together	(888) 495 8020	http://www.tenantstogether.org/tenant-rights-hotline	Provides tenant counseling over the phone to tenants across the state certain days of the week.	Legal/Housing	Counseling	474 Valencia St #156, San Francisco, CA 94103
National	National	U.S. Dept. of Housing and Urban Development 	(202) 708-1112 	https://portal.hud.gov/hudportal/HUD	HUD's mission is to create strong, sustainable, inclusive communities and quality affordable homes for all.	Legal/Housing	Housing. Federal	451 7th Street S.W., Washington, DC 20410
National	National	U.S. Dept. of Housing and Urban Development Multifamily Housing	(202) 708-1112 	https://portal.hud.gov/hudportal/HUD?src=/program_offices/housing/mfh	This inventory is designed to assist prospective applicants with locating units in HUD insured and HUD subsidized multifamily properties that serve the elderly and/or persons with disabilities.	Legal/Housing	Housing, Federal	451 7th Street S.W., Washington, DC 20410
San Francisco	San Francisco	Volunteer Eviction Assistance	(408) 280-2424	https://mvtenantscoalition.org/legal-resources/	Short-term pro-bono assistance with eviction complaints Fridays by appointment.	Legal/Housing	Legal Aid	474 Valencia St #156, San Francisco, CA 94103
Santa Clara	San Jose 	Waiting List Hotline	408-926-8885	https://www.sccgov.org/sites/oir/Documents/sj-hmls-svcs-guide.pdf	The two shelters for families with children who share a common waiting list. In order to get on this waiting list, call the number above between 10:00 a.m. and 11:00 a.m. Monday through Friday. Households must call this number daily at that time to remain on the waiting list.	Shelter	Shelters for Families with Children	n/a`
