export const resources = `
county	city	organization	phone	website	description	tags	address
National	National	(Information and Technical Assistance with) The Americans with Disabilities Act	ADA Information Line 800-514-0301 (voice); 800-514-0383 (TTY)	https://www.ada.gov/infoline.htm	The Department of Justice operates a toll-free ADA Information Line to provide information and materials to the public about the requirements of the ADA. ADA Specialists, who assist callers in understanding how the ADA applies to their situation, are available on Monday, Tuesday, Wednesday, and Friday from 9:30 a.m. until 5:30 p.m. (Eastern Time) and on Thursday from 12:30 p.m. until 5:30 p.m. (Eastern Time). Calls are confidential.	Legal AId, Civil Rights	U.S. Department of Justice 950 Pennsylvania Avenue, NW, Civil Rights Division, Disability Rights Section - NYA , Washington, D.C. 20530
Santa Clara	San Jose	Affordable Housing Search Center	1-877-428-8844	http://www.scchousingsearch.org/	Free housing search database and support center.	Housing	PO Box 35305, Charlotte, NC, 28235
Santa Clara	San Jose	ASIAN AMERICANS FOR COMMUNITY INVOLVEMENT OF SANTA CLARA COUNTY, INC	  408-975-2730	http://aaci.org/	It’s not uncommon for Asians and other minorities to feel uncomfortable seeking and receiving services due to language and cultural barriers. The team of multicultural and multilingual professionals at AACI works to bridge these gaps through an array of services and programs in health, recovery, advocacy, shelter and community. The AACI team includes the following specialists: Physicians, Psychiatrists, Psychologists, Social workers, Marriage and family therapist, Teachers, Health educators, Domestic violence prevention specialists.	Senior Support, Cultural Empowerment	2400 Moorpark Ave, San Jose, CA 95128
Santa Clara	San Jose	Asian Law Alliance	(408) 287-9710	http://asianlawalliance.org/	Provides free legal representation to tenants with housing problems.	Legal Aid	991 W Hedding St, San Jose, CA 95126
Santa Clara	Los Gatos	Bay Area Housing Corporation	408-975-2730	http://bahc1.org/	Bay Area Housing Corporation’s mission is to improve the lives of people with developmental disabilities and their families and other low income populations by creating and maintaining quality housing opportunities that meet the needs of the individual.	Housing, disabilities	101 Church Street, Suite 4, Los Gatos, CA 95030
Santa Clara	San Jose	Bay Area Legal Aid	(408) 850-7066	https://baylegal.org/	Provides free legal representation to low-income tenants with housing problems.	Legal Aid, County	4 N 2nd St #600, San Jose, CA 95113
Santa Clara	Santa Clara	BILL WILSON CENTER	  1-408-243-0222	www.billwilsoncenter.org	The Homeless Youth Drop-In Center, located in downtown San Jose, is a safe place where young people can begin to form bonds with caring adults and access essential resources for their overall well-being. The primary goal of the program is to get homeless youth into safe and permanent housing.	Housing, Shelter, counseling	3490 The Alameda, Santa Clara, CA 95050
State WIde	State WIde	California Department of Fair Employment and Housing	1-800-233-3212	http://www.dfeh.ca.gov/	State agency responsible for taking complaints of housing discrimination.	Discrimination, State	mailing: 2218 Kausen Drive, Suite 100, Elk Grove, CA 95758
Santa Clara	San Jose 	CATHOLIC CHARITIES OF SANTA CLARA COUNTY	  408-846-0428	www.ccsj.org	Senior Nutrition Program	RLEI, Housing, Mental heatlh, DACA renewals, Community Development	2625 Zanker Rd, San Jose, CA 95134
Santa Clara	Campbell	CITY OF CAMPBELL RECREATION AND COMMUNITY SERVICES	  1-408-866-2764	www.cityofcampbell.com	The Lunch Program offers nutritious meals Monday-Friday.	Recreation, Community	Campbell Community Center, 1 W. Campbell Ave., Office C-31, Campbell, CA 95008
Santa Clara	Milpitas	CITY OF MILPITAS RECREATION SERVICES DEPARTMENT	  1-408-586-2425	http://www.ci.milpitas.ca.gov/milpitas/departments/recreation-services/	Offers a senior nutrition lunch program at the Senior Center.	Recreation, Community	457 East Calaveras Blvd., Milpitas, CA 95035
Santa Clara	San Jose 	City of San Jose - Code Enforcement 	(408)535-7770	http://www.sanjoseca.gov/codeEnforcement	Enforces Housing Code and other City code.	Housing	200 E Santa Clara St, San Jose, CA 95113
Santa Clara	San Jose 	City of San Jose - Rental Rights & Referral Program	(408)975-4480	http://www.sanjoseca.gov/index.aspx?NID=743	Rent increases and service reductions in mobilehomes and most tri-plex and larger buildings built before 9/7/79.	Housing	200 E. Santa Clara St., San Jose, CA 95113
Santa Clara	San Jose 	CITY OF SAN JOSE DEPARTMENT OF PARKS, RECREATION AND NEIGHBORHOOD SERVICES	  408-535-3570	http://www.sanjoseculture.org/index.aspx?NID=204	Senior Nutrition Program	Recreation, Community, San Jose	200 E Santa Clara St, San Jose, CA 95113
Santa Clara	San Jose	CITY OF SUNNYVALE COMMUNITY SERVICES	  1-408-730-7360	http://svcommunityservices.org/	Offers educational, recreational and cultural activities for seniors.	Education, Seniors	725 Kifer Rd, Sunnyvale, CA 94086
Santa Clara	San Jose	​City Team – Rescue Mission	408-288-2153	https://www.cityteam.org/san-jose/	Overnight emergency shelter for men; check-in begins at 5:30 p.m. First come, first served.	Adult shelter	1174 Old Bayshore Highway, San Jose, CA 95112
San Mateo County	East Palo Alto 	Community Legal Services East Palo Alto	650-326-6440	https://clsepa.org/	Provides free legal aid to tenants.	Outside San Jose, Legal Aid	1861 Bay Road East Palo Alto, CA 94303
Santa Clara	Mountain View	COMMUNITY SERVICES AGENCY OF MOUNTAIN VIEW AND LOS ALTOS	  1-650-964-6586	www.csacares.org/senior-services	Mountain View Senior Nutrition Program	Recreation, Community, San Jose	204 Stierlin Rd, Mountain View, CA 94043
Santa Clara	Palo Alto	COMMUNITY WORKING GROUP - OPPORTUNITY CENTER	(650) 299-8700	https://communityworkinggroup.org/cwg-housing/opportunity-center/	Offers drop-in services, showers and laundry facilities, lockers, light snacks, information and referral, transportation assistance, a clothes closet, medical and psychiatric screening and referral, inter-faith chaplaincy, and fellowship.	Community, Supportive Housing	2507-A Alma Street Palo Alto, CA 94301
Santa Clara	Gilroy	GILROY COMPASSION CENTER	  1-408-763-7120	https://gilroycompassioncenter.blogspot.com/	Offers bathroom, resource listings, jackets, clothing, telephone, the internet, laundry, mail, messages, compassion, and respite from the street. Shower, laundry, and medical service available every Thursday starting at 10am and finishing at 12pm. Hot Meals.	Resources	370 Tomkins Ct, Gilroy, CA 95020
Santa Clara	San Jose	HomeFirst - Veterans Services	408-510-7522	https://www.homefirstscc.org/our-programs/	Emergency Shelter and Transitional Housing for veterans; veterans can access first come first served shelter beds (check in at 3:30 p.m.) before being screened for veteran bed eligibility.	Shelters for Veterans 	2011 Little Orchard Street, San Jose, CA, 95125
Santa Clara	San Jose	HomeFirst – Boccardo Reception Center	408-294-2100	https://www.homefirstscc.org/our-programs/	Emergency shelter for men and women; check-in begins at 3:30 p.m. First come, first served.	Shelter for Adults Without Children	2011 Little Orchard Street, San Jose, CA 95125
Santa Clara	San Jose	Santa Clara County Housing Authority	(408) 275-8770	https://www.scchousingauthority.org/contact/	Provides affordable housing assistance and manages the Housing Choice Voucher (Section 8) program.	Housing, Section 8	505 West Julian Street, San José, CA 95110
Santa Clara	San Jose	Housing Helpline	(408) 510-7600	http://www.sanjoseca.gov/index.aspx?NID=738	Information on service agencies and housing opportunities for homeless individuals.	Housing	200 E. Santa Clara St., San Jose, CA 95113
National	National	US Department of Housing and Urban Development	1-800-569-4287	https://www.hud.gov/i_want_to/talk_to_a_housing_counselor	Advice on buying a home, renting, default, foreclosure avoidance, credit issues or reverse mortgages.	Housing	U.S. Department of Housing and Urban Development 451 7th Street S.W., Washington, DC 20410
Santa Clara	Los Gatos	Information and Referral Services	(408) 243-8565	n/a	Collection of resources and referrals for renters.	n/a	n/a
Santa Clara	Campbell	Information and Referral Services  	(408) 243-8565	n/a	Collection of resources and referrals for renters.	Mediation, Counseling	n/a
Santa Clara	San Jose	JTS Northside Senior Community Center	  1-408-343-7711	https://jtsnorthsidecc.wordpress.com/about/	Senior Wellness Program	Senior	488 North Sixth Street, San Jose, CA 95112
Santa Clara	San Jose	Law Foundation of Silicon Valley - Fair Housing Law Project	(408) 280-2452	http://www.lawfoundation.org/fair-housing-law-project-fhlp	Provides free legal representation to victims of housing discrimination.	Discimination, Legal Aid, County	152 North 3rd Street, 3rd Floor, San Jose, CA 95112
Santa Clara	San Jose	Law Foundation of Silicon Valley - Health Legal Services	(408) 280-2430	http://www.lawfoundation.org/health-legal-services-hls/	Provides free legal representation to individuals with HIV/AIDS or diabetes who have housing problems.	Legal Aid, Elderly/Disabled, County	152 North 3rd Street, 3rd Floor, San Jose, CA 95112
Santa Clara	San Jose	Law Foundation of Silicon Valley - Mental Health Advocacy Project	(408) 280-2420 	http://www.lawfoundation.org/mental-health-advocacy-project-mhap/	Provides free legal representation to mental health and developmental services consumers who have housing problems.	Legal Aid, Elderly, Disabled, County	152 North 3rd Street, 3rd Floor, San Jose, CA 95112
Santa Clara	San Jose	LifeMoves – Georgia Travis House	408-271-1630	https://lifemoves.org/the-problem/get-help/santa-clara-county/	Shelter for women; call for more information.	Shelter for Adults Without Children	260 Commercial Street San Jose, CA 95112
Santa Clara	San Jose	LifeMoves – Montgomery Street Inn	408-271-5160	https://lifemoves.org/the-problem/get-help/santa-clara-county/	Emergency shelter for men; program assessments Monday through Friday at 12:30 p.m.	Shelter for Adults Without Children	358 North Montgomery Street, San Jose, CA 95110
Santa Clara	Los Altos	Los Altos Mediation Program	(650) 949-5267	http://losaltoscf.org/losaltosdispute/about-the-los-altos-dispute-resolution-services/	Information and mediation	Outside San Jose, Counseling	1490 El Camino Real, Santa Clara, CA 95050
Santa Clara	Los Gatos	Los Gatos Information and Referral Services	(408)243-8565	https://www.losgatosca.gov/DocumentCenter/View/8792	Information, counseling and mediation Apartment and mobilehome rent control	Outside San Jose, Counseling	110 E. Main St., Los Gatos, CA 95030
Santa Clara	San Jose	MARTHA'S KITCHEN	408.293.6111 	www.marthas-kitchen.org	Provides meals to men, women, and children.	Meals, showers, laundry	311 WILLOW STREET, SAN JOSE, CA 95110
Santa Clara	Mountain View 	MTVW Information and Referral	(650) 960-0495	http://santaclara.networkofcare.org/mh/services/agency.aspx?pid=ProjectSentinelSunnyvale_356_2_0	Provides information and counseling on tenant/landlord rights and responsibilities. Conciliation and mediation services available for rental housing, and neighborhood disputes. Serves Cupertino, Milpitas, Mountain View ((650) 960-0495), Santa Clara, Sunnyvale, Campbell, Palo Alto ((650) 856-4062), Los Gatos ((408) 402-0307), Gilroy, Morgan Hill.	Legal Aid, Housing	554 Valley Way, Milpitas, CA 95035
Santa Clara	Palo Alto 	Palo Alto Mediation Service	(650) 856-4062	http://www.tenantstogether.org/resources/palo-alto-mediation-program	Information, counseling and mediation.	Outside San Jose, Counseling	450 Bryant Street, Palo Alto, CA 94301
Santa Clara	San Jose	PORTUGUESE ORGANIZATION FOR SOCIAL SERVICES AND OPPORTUNITIES	1-408-293-0877	portuguesecenter.org	Services include senior nutrition, escorting to doctors visits, translation services, and case management.	Senior, nutrition, health	1115 East Santa Clara Street, San Jose, California 95116
Santa Clara	San Jose	Pro Bono Project Lawyers in the Library	(408) 808-2382	https://events.sjpl.org/event/lawyers_in_the_library_spring2016	Provides free 20-minute legal consultation on a variety of legal matters.	Legal Aid	Dr. Martin Luther King, Jr. Library, Room 255, 150 E. San Fernando St. San José, CA 95112
Santa Clara	Fremont	Project Sentinel	1-888-331-3332	http://housing.org/	Provides a variety of services (including mediation services) and advice regarding landlord-tenant problems in some jurisdictions.  Investigates claims of housing discrimination.	Legal Aid, Discrimination	39155 Liberty Street, Ste. D440, Fremont, CA 94538
Santa Clara	San Jose	Senior Adult Legal Assistance	408 295-5991	http://www.sala.org/	Legal assistance for individuals 60+ years old. Free legal assistance with: Housing, public benefits, long term care, elder abuse, etc.	Legal Aid, Elderly	1425 Koll Circle, Suite 109, San Jose, CA 95112
Santa Clara	San Jose	Salvation Army – Emmanuel House	408-282-1175	 http://www.salvationarmysiliconvalley.org/santaclara/emmanuel_house	Emergency shelter for men; suggested arrival time is between 1:30 p.m. to 2:30 p.m.	Shelter for Adults Without Children	405 North Fourth Street, San Jose, CA 95112
Santa Clara	San Jose	Santa Clara County Bar Association Lawyer Referral	(408)287-2557	https://www.sccba.com/?lrs	Referrals to private attorneys (commercial rent disputes, other legal problems)	Legal Aid, Dispute Resolution	31 North 2nd St., Ste. 400, San Jose, CA 95113
Santa Clara	San Jose	SCC Department of Human Relations, Dispute Resolution Services	(408) 792-2314	https://www.sccgov.org/sites/ohr/Community/Pages/default.aspx	Provides low cost neutral-third-party dispute resolution services between tenants and landlords, tenants and other tenants, and neighbors.	Dispute Resolution	2310 North 1st Street, Suite 100, San Jose, CA 95131
Santa Clara	San Jose	SECOND HARVEST FOOD BANK OF SANTA CLARA AND SAN MATEO COUNTIES	(408) 266-8866	www.shfb.org	Food Connection Hotline	Food	750 Curtner Avenue, San Jose CA 95125
Santa Clara	San Jose	Senior Adult Legal Assistance	(408)295-5991	http://www.sala.org/	Legal assistance for individuals 60+ years old.	Legal Aid, Elderly, Disabled	160 E Virginia St, San Jose, CA 95112
Santa Clara	San Jose	Sheriff's Office Civil Division  	(408) 808-4800	https://www.sccgov.org/sites/sheriff/Pages/civil.aspx	Information on evictions, fees and levies.	Law Enforcement	55 West Younger Ave., San Jose CA 95110
Santa Clara	San Jose 	SJPD Non-Emergency Line  	(408) 277-8900	http://www.sjpd.org/InsideSJPD/PhoneList.html	Assistance with civil standbys and other non-emergency issues .	Law Enforcement	201 W Mission Street, San Jose, CA 95110
Santa Clara	San Jose 	Small Claims Advisor 	(408) 882-2100 (option #2, 6)	https://www.lawhelpca.org/org/santa-clara-superior-court-small-claims-advisor	Information on starting a claim, going to court, and questions about judgments.	Legal Aid, Information	191 N 1st St, San Jose, CA 95113
Santa Clara	San Jose 	ST. JOSEPH'S CATHEDRAL SOCIAL MINISTRY OFFICE	  1-408-283-8100	http://www.stjosephcathedral.org/ministries/social-ministry/	Offers a safe place for the homeless to receive mail while living in a shelter, phone service available to make appointments and receive messages, sandwiches and something to drink, once a week grocery food bag and referrals to shelter, clothing, housing and community resources.	Food, Clothing, Comunication Resources	80 S Market St, San Jose, CA 95113
Santa Clara	Sunnyvale	ST. THOMAS EPISCOPAL CHURCH	(408) 736-4155	www.stthomas-svale.org	Offers hot meals three days a week to hungry people without restriction.	Food	231 Sunset Avenue, Sunnyvale, CA 94086
Santa Clara	San Jose 	Superior Court - Civil Division 	(408) 882-2700	http://www.scscourt.org/court_divisions/civil/civil_home.shtml	Information on civil cases, civil filings, Unlawful Detainers (eviction), and Alternative Dispute Resolution (ADR) .	Legal	191 N 1st St, San Jose, CA 95113
San Francisco County	San Francisco	Tenants Together	(888) 495 8020	http://www.tenantstogether.org/tenant-rights-hotline	Provides tenant counseling over the phone to tenants across the state certain days of the week.	Counseling	474 Valencia St #156, San Francisco, CA 94103
National	National	U.S. Dept. of Housing and Urban Development 	(202) 708-1112 	https://portal.hud.gov/hudportal/HUD	HUD's mission is to create strong, sustainable, inclusive communities and quality affordable homes for all.	Housing. Federal	451 7th Street S.W., Washington, DC 20410
National	National	U.S. Dept. of Housing and Urban Development Multifamily Housing	(202) 708-1112 	https://portal.hud.gov/hudportal/HUD?src=/program_offices/housing/mfh	This inventory is designed to assist prospective applicants with locating units in HUD insured and HUD subsidized multifamily properties that serve the elderly and/or persons with disabilities.	Housing, Federal	451 7th Street S.W., Washington, DC 20410
San Francisco	San Francisco	Volunteer Eviction Assistance	(408) 280-2424	https://mvtenantscoalition.org/legal-resources/	Short-term pro-bono assistance with eviction complaints Fridays by appointment.	Legal Aid	474 Valencia St #156, San Francisco, CA 94103
Santa Clara	San Jose 	Waiting List Hotline	408-926-8885	https://www.sccgov.org/sites/oir/Documents/sj-hmls-svcs-guide.pdf	The two shelters for families with children who share a common waiting list. In order to get on this waiting list, call the number above between 10:00 a.m. and 11:00 a.m. Monday through Friday. Households must call this number daily at that time to remain on the waiting list.	Shelters for Families with Children	n/a
Santa Clara	San Jose 	YU-AI-KAI	1-408-294-2505	www.yuaikai.org	Senior Services	Senior, Cultural Empowerment	588 N 4th St, San Jose, CA 95112`
