export const resources = `
geo	county	city	organization	phone	website	description	language	category	address
County-SanMateo, County-SantaClara	Santa Clara	Palo Alto	Community Working Group - Opportunity Center	650-299-8700	https://communityworkinggroup.org/cwg-housing/opportunity-center/	Community Working Group's Opportunity Center of the Midpeninsula, is an affordable apartment complex and service center for homeless and extremely low-income families and individuals. 	english	afforable_housing, social_service, shelter	2507-A Alma Street Palo Alto, CA 94301
County-SantaClara	Santa Clara	San Jose	Affordable Housing Search Center	1-877-428-8844	http://www.scchousingsearch.org/	Free housing search database and support center for Santa Clara county. The service also provides links to housing resources and helpful tools for renters such as an affordability calculator, rental checklist, and information about renter rights and responsibilities.	english, spanish	affordable_housing	200 E Santa Clara St, San Jose, CA 95113
County-SantaClara	Santa Clara	Los Gatos	Bay Area Housing Corporation	408-975-2730	http://bahc1.org/	Bay Area Housing Corporation’s mission is to improve the lives of people with developmental disabilities and their families and other low income populations by creating and maintaining quality housing opportunities that meet the needs of the individual.	english	affordable_housing	101 Church Street, Suite 4, Los Gatos, CA 95030
County-SantaClara	Santa Clara	Santa Clara	Santa Clara County Housing Authority	408-275-8770	https://www.scchousingauthority.org/	The agency assists about 17,000 households through the federal rental housing assistance (Housing Choice Voucher, also known as Section 8) program	english	affordable_housing	505 West Julian Street San Jose, CA 95110
City-Campbell	Santa Clara	Campbell	City of Campbell - Community Development	408-866-2764	http://www.cityofcampbell.com/135/Housing	Services include landlord tenant disputes, rental increase meditation, affordable housing referrals, first time home buyer program, and home repair loans	english	affordable_housing, legal_aid	Campbell Community Center, 1 W. Campbell Ave., Office C-31, Campbell, CA 95008
City-SanJose	Santa Clara	San Jose 	City of San Jose - Rental Rights & Referral Program	408-975-4480	http://www.sanjoseca.gov/index.aspx?NID=743	Information on San Jose's apartment rent ordinance, tenant protection ordinance. The Housing Department also maintains a List of Affordable Apartments in San Jose.	english	affordable_housing, legal_aid	200 E. Santa Clara St., San Jose, CA 95113
City-MountainView, City-LosAltos, City-LosAltosHills	Santa Clara	Mountain View	Community Services Agency	650-964-6586	https://www.csacares.org/services/homeless-services/	CSA homeless case managers assist with: Information to locate and secure affordable housing, assistance with public transportation, benefits and health services. Financial assistance with one month’s rent once clients, and secure employment and a place to live that fits within their budget. Food is also available through our Food & Nutrition Center	english	affordable_housing, legal_aid	204 Stierlin Rd, Mountain View, CA 94043
City-LosAltos	Santa Clara	Los Altos	Los Altos Mediation Program	650-949-5267	http://losaltoscf.org/losaltosdispute/about-the-los-altos-dispute-resolution-services/	Information and mediation including: Information on rights and responsibilities for tenants and landlords (deposits, rent increases, maintenance, eviction)	english	legal_aid	1490 El Camino Real, Santa Clara, CA 95050
City-PaloAlto	Santa Clara	Palo Alto 	Palo Alto Mediation Service	650-856-4062	http://www.tenantstogether.org/resources/palo-alto-mediation-program	Information, counseling and mediation.	english	legal_aid	450 Bryant Street, Palo Alto, CA 94301
City-SanJose	Santa Clara	San Jose	Pro Bono Project Lawyers in the Library	408-808-2382	https://events.sjpl.org/event/lawyers_in_the_library_spring2016	Provides free 20-minute legal consultation on a variety of legal matters.	english	legal_aid	Dr. Martin Luther King, Jr. Library, Room 255, 150 E. San Fernando St. San José, CA 95112
County-SantaClara	Santa Clara	San Jose	Senior Adult Legal Assistance	408-295-5991	http://www.sala.org/	Legal assistance for individuals 60+ years old. Free legal assistance with: Housing, public benefits, long term care, elder abuse, etc.	english	legal_aid	1425 Koll Circle, Suite 109, San Jose, CA 95112
County-SantaClara	Santa Clara	San Jose	Santa Clara County Bar Association Lawyer Referral	408-287-2557	https://sccba.community.lawyer/	Receive 30-minute consultation with a qualified local lawyer in the area of legal expertise you require. Consultation will be immediately arranged usually within 24-48 hours. Receive a free second 30-minute appointment with a different lawyer, if requested.	english, spanish	legal_aid	31 North 2nd St., Ste. 400, San Jose, CA 95113
County-SantaClara	Santa Clara	Fremont	Project Sentinel	1-888-331-3332	http://housing.org/fair-housing/fair-housing-resources/	Provides a variety of services (including mediation services) and advice regarding landlord-tenant problems in some jurisdictions.  Investigates claims of housing discrimination.	english, spanish, chinese, vietnamese, tagalog, russian, korean	legal_aid	39155 Liberty Street, Ste. D440, Fremont, CA 94538
County-SantaClara	Santa Clara	San Jose	Law Foundation of Silicon Valley - Fair Housing Law Project	408-280-2452	http://www.lawfoundation.org/fair-housing-law-project-fhlp	Provides free legal representation to victims of housing discrimination.	english, spanish	legal_aid	152 North 3rd Street, 3rd Floor, San Jose, CA 95112
City-SanJose	Santa Clara	San Jose	HomeFirst – Boccardo Reception Center	408-294-2100	https://www.homefirstscc.org/our-programs/	Emergency shelter for men and women; check-in begins at 3:30 p.m. First come, first served.	english	shelter	2011 Little Orchard Street, San Jose, CA 95125
City-SanJose	Santa Clara	San Jose	Housing Helpline	408-510-7600	http://www.sanjoseca.gov/index.aspx?NID=738	Information on service agencies and housing opportunities for homeless individuals.	english, spanish	shelter	200 E. Santa Clara St., San Jose, CA 95113
City-SanJose	Santa Clara	San Jose	LifeMoves – Georgia Travis House	408-271-1630	https://lifemoves.org/the-problem/get-help/santa-clara-county/	Shelter for women; call for more information.	english	shelter	260 Commercial Street San Jose, CA 95112
City-SanJose	Santa Clara	San Jose	LifeMoves – Montgomery Street Inn	408-271-5160	https://lifemoves.org/the-problem/get-help/santa-clara-county/	Emergency shelter for men; program assessments Monday through Friday at 12:30 p.m.	english	shelter	358 North Montgomery Street, San Jose, CA 95110
City-SanJose	Santa Clara	San Jose	Salvation Army – Emmanuel House	408-282-1175	 http://www.salvationarmysiliconvalley.org/santaclara/emmanuel_house	Emergency shelter for men; suggested arrival time is between 1:30 p.m. to 2:30 p.m.	english	shelter	405 North Fourth Street, San Jose, CA 95112
County-SantaClara	Santa Clara	San Jose	Asian Americans for Community Involvement	408-975-2730	http://aaci.org/	The team of multicultural and multilingual professionals at AACI works to bridge these gaps through an array of services and programs in health, recovery, advocacy, shelter and community. The AACI team includes the following specialists: Physicians, Psychiatrists, Psychologists, Social workers, Marriage and family therapist, Teachers, Health educators, Domestic violence prevention specialists.	english	shelter, social_service	2400 Moorpark Ave, San Jose, CA 95128
City-SanJose	Santa Clara	San Jose	Cityteam San Jose	408-288-2153	https://www.cityteam.org/san-jose/	Overnight emergency shelter for men; check-in begins at 5:30 p.m. First come, first served.	english	shelter, social_service	1174 Old Bayshore Highway, San Jose, CA 95112
County-SantaClara	Santa Clara	Santa Clara	Bill Wilson Center	408-243-0222	http://www.billwilsoncenter.org	The Homeless Youth Drop-In Center, located in downtown San Jose, is a safe place where young people can begin to form bonds with caring adults and access essential resources for their overall well-being. The primary goal of the program is to get homeless youth into safe and permanent housing.	english	shelter, social_services	3490 The Alameda, Santa Clara, CA 95050
City-Sunnyvale	Santa Clara	Sunnyvale	Sunnyvale Community Services	408-730-7360	http://svcommunityservices.org/	Sunnyvale Community Services provides emergency assistance, information/referral services, and food programs to families, individuals, and seniors living in Sunnyvale zip codes: 94085, 94086, 94087, 94088, and 94089.	english, spanish, chinese, vietnamese, tagalog, russian	social_service	725 Kifer Rd, Sunnyvale, CA 94086
County-SantaClara	Santa Clara	San Jose	Asian Law Alliance	408-287-9710	http://asianlawalliance.org/	Provides free legal representation to tenants with housing problems.	english, chinese, vietnamese, tagalog, korean	social_service, legal_aid	991 W Hedding St, San Jose, CA 95126
County-SantaClara	Santa Clara	San Jose	Bay Area Legal Aid	408-850-7066	https://baylegal.org/	Provides free legal representation to low-income tenants with housing problems.	english	social_service, legal_aid	4 N 2nd St #600, San Jose, CA 95113
County-SanMateo	San Mateo County	East Palo Alto 	Community Legal Services East Palo Alto	650-326-6440	https://clsepa.org/	Provides free legal aid to tenants.	english	social_service, legal_aid	1861 Bay Road East Palo Alto, CA 94303
County-SantaClara	Santa Clara	San Jose 	Catholic Charities of Santa Clara County	408-846-0428	http://www.ccsj.org	Services include job skills training and placement, older adult services, mental health and substance abuse counseling, housing assistance, financial education, immigration support, and refugee resettlement.	english	social_services, affordable_housing	2625 Zanker Rd, San Jose, CA 95134`
