Rails.application.routes.draw do
  root to: 'renters_rights#index'
  # reference: http://guides.rubyonrails.org/routing.html
  get '/about', to: 'renters_rights#about'
  get '/eviction', to: 'renters_rights#eviction'
  get '/resources/:filter', to: 'renters_rights#resources'
  get '/rent-calculator', to: 'renters_rights#rent_calculator'
  get '/legal-aid', to: 'renters_rights#legal_aid'
  get '/shelter', to: 'renters_rights#shelter'
  get '/report-issue', to: 'renters_rights#report_issue'
  get '/find-jurisdiction', to: 'renters_rights#find_jurisdiction'
  get '/rent-increase', to: 'renters_rights#rent_increase'
  get '/not-applicable', to: 'renters_rights#not_applicable'
  get '/renters-types', to: 'renters_rights#renters_types'
  get '/renters-aro_tpo', to: 'renters_rights#renters_aro_tpo'
  get '/renters-duplex', to: 'renters_rights#renters_duplex'
  get '/address-check', to: 'renters_rights#address_check'
  post '/address-check', to: 'renters_rights#address_check_post' 
  # get '/:locale', to: 'renters_rights#index'
  # get '/:locale/about', to: 'renters_rights#faq'
  # get '/:locale/renters', to: 'renters_rights#renters'
  # get '/:locale/eviction', to: 'renters_rights#eviction'
  # get '/:locale/resources', to: 'renters_rights#resources'
  # get '/:locale/rent-calculator', to: 'renters_rights#rent_calculator'
end
